[package]
name = "github-openapi-builder"
version = "0.1.1"
license = "MIT"
authors = ["Greg \"GothAck\" Miell <rust@greg.gothack.ninja>"]
description = "Github OpenAPI Structs"
homepage = "https://github.com/GothAck/rust-github-openapi"
repository = "https://github.com/GothAck/rust-github-openapi"
readme = "README.md"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
clap = "3.0.0-beta.5"
codegen2 = "0.1"
convert_case = "0.4"
env_logger = "0.9"
log = "0.4"
openapiv3 = "0.5"
serde_json = "1"
serde_yaml = "0.8"
